// This is generated by writeCoreEval; please edit!
/* eslint-disable */

const manifestBundleRef = {bundleID:"b1-75a6dcf26c8e4bf91e992118f914294d91ec8ee62ada0b896a510c773edeb3b9b81105bbde177c374710eadbc43b501a91aa20f6749c1144960680f772eff16c"};
const getManifestCall = harden([
  "getManifest",
  {
    installKeys: {
      ElysContract: {
        bundleID: "b1-fbd6c57baea93b439b5acc14061b68627003817b6f89285f02e0c824d2869df90774d151fe13fc2d3f8b2fd498ef0e3ec32ad67ada9f0dd34225ea38ef129d5a",
      },
    },
    options: {
      assetInfo: [
        [
          "ubld",
          {
            baseDenom: "ubld",
            baseName: "agoric",
            chainName: "agoric",
          },
        ],
        [
          "uatom",
          {
            baseDenom: "uatom",
            baseName: "cosmoshub",
            chainName: "cosmoshub",
          },
        ],
        [
          "ibc/F00782820450D9F76025F7FC25BF026EC11309069CE89C1CD326311033E17E3E",
          {
            baseDenom: "uatom",
            baseName: "cosmoshub",
            chainName: "agoric",
          },
        ],
        [
          "ibc/21C0EAD61CEFFD2846271C8E00CAD4A0C972E9D867E039D56F9A7F07D2AEC03D",
          {
            baseDenom: "62DB20C9CA04889D1AFF93CDB098619D662942027B5C8AF995F11BCE8B480BF6",
            baseName: "elys",
            chainName: "agoric",
          },
        ],
        [
          "ustrd",
          {
            baseDenom: "ustrd",
            baseName: "stride",
            chainName: "stride",
          },
        ],
        [
          "uelys",
          {
            baseDenom: "uelys",
            baseName: "elys",
            chainName: "elys",
          },
        ],
        [
          "utia",
          {
            baseDenom: "utia",
            baseName: "celestia",
            chainName: "celestia",
          },
        ],
        [
          "ibc/510D1969E876B0DCE9EE450CEC7BF987164CF9E4E42516FF972EDDBA9B64BE09",
          {
            baseDenom: "utia",
            baseName: "celestia",
            chainName: "agoric",
          },
        ],
        [
          "ibc/627650D6C650F179DDBD708591E613345910985F5549DB1F6991020B101EE8E0",
          {
            baseDenom: "D02B2CC73ABD49D2746AF67980F7CDD93A54B0AFF8C75EFA095B0423B8950653",
            baseName: "elys",
            chainName: "agoric",
          },
        ],
      ],
      chainInfo: {
        agoric: {
          bech32Prefix: "agoric",
          chainId: "agoricdev-25",
          connections: {
            "elysicstestnet-1": {
              client_id: "07-tendermint-16",
              counterparty: {
                client_id: "07-tendermint-17",
                connection_id: "connection-10",
              },
              id: "connection-16",
              state: 3,
              transferChannel: {
                channelId: "channel-23",
                counterPartyChannelId: "channel-11",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "mocha-4": {
              client_id: "07-tendermint-21",
              counterparty: {
                client_id: "07-tendermint-21",
                connection_id: "connection-662",
              },
              id: "connection-18",
              state: 3,
              transferChannel: {
                channelId: "channel-129",
                counterPartyChannelId: "channel-399",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            provider: {
              client_id: "07-tendermint-18",
              counterparty: {
                client_id: "07-tendermint-311",
                connection_id: "connection-224",
              },
              id: "connection-17",
              state: 3,
              transferChannel: {
                channelId: "channel-25",
                counterPartyChannelId: "channel-388",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "stride-internal-1": {
              client_id: "07-tendermint-15",
              counterparty: {
                client_id: "07-tendermint-68",
                connection_id: "connection-44",
              },
              id: "connection-15",
              state: 3,
              transferChannel: {
                channelId: "channel-13",
                counterPartyChannelId: "channel-60",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          icaEnabled: false,
          icqEnabled: false,
          namespace: "cosmos",
          pfmEnabled: true,
          reference: "agoricdev-25",
          stakingTokens: [
            {
              denom: "ubld",
            },
          ],
        },
        celestia: {
          bech32Prefix: "celestia",
          chainId: "mocha-4",
          connections: {
            "agoricdev-25": {
              client_id: "07-tendermint-21",
              counterparty: {
                client_id: "07-tendermint-21",
                connection_id: "connection-662",
              },
              id: "connection-18",
              state: 3,
              transferChannel: {
                channelId: "channel-399",
                counterPartyChannelId: "channel-129",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "stride-internal-1": {
              client_id: "07-tendermint-367",
              counterparty: {
                client_id: "07-tendermint-367",
                connection_id: "connection-281",
              },
              id: "connection-26",
              state: 3,
              transferChannel: {
                channelId: "channel-78",
                counterPartyChannelId: "channel-38",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          icaEnabled: true,
          icqEnabled: false,
          namespace: "cosmos",
          pfmEnabled: true,
          reference: "mocha-4",
          stakingTokens: [
            {
              denom: "utia",
            },
          ],
        },
        cosmoshub: {
          bech32Prefix: "cosmos",
          chainId: "provider",
          connections: {
            "agoricdev-25": {
              client_id: "07-tendermint-311",
              counterparty: {
                client_id: "07-tendermint-18",
                connection_id: "connection-17",
              },
              id: "connection-224",
              state: 3,
              transferChannel: {
                channelId: "channel-388",
                counterPartyChannelId: "channel-25",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "stride-internal-1": {
              client_id: "07-tendermint-317",
              counterparty: {
                client_id: "07-tendermint-70",
                connection_id: "connection-48",
              },
              id: "connection-225",
              state: 3,
              transferChannel: {
                channelId: "channel-389",
                counterPartyChannelId: "channel-62",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          icaEnabled: true,
          icqEnabled: false,
          namespace: "cosmos",
          pfmEnabled: true,
          reference: "provider",
          stakingTokens: [
            {
              denom: "uatom",
            },
          ],
        },
        elys: {
          bech32Prefix: "elys",
          chainId: "elysicstestnet-1",
          connections: {
            "agoricdev-25": {
              client_id: "07-tendermint-17",
              counterparty: {
                client_id: "07-tendermint-16",
                connection_id: "connection-16",
              },
              id: "connection-10",
              state: 3,
              transferChannel: {
                channelId: "channel-11",
                counterPartyChannelId: "channel-23",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "stride-internal-1": {
              client_id: "07-tendermint-19",
              counterparty: {
                client_id: "07-tendermint-69",
                connection_id: "connection-46",
              },
              id: "connection-11",
              state: 3,
              transferChannel: {
                channelId: "channel-12",
                counterPartyChannelId: "channel-61",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          icaEnabled: false,
          icqEnabled: false,
          namespace: "cosmos",
          pfmEnabled: false,
          reference: "elysicstestnet-1",
          stakingTokens: [
            {
              denom: "uelys",
            },
          ],
        },
        stride: {
          bech32Prefix: "stride",
          chainId: "stride-internal-1",
          connections: {
            "agoricdev-25": {
              client_id: "07-tendermint-68",
              counterparty: {
                client_id: "07-tendermint-15",
                connection_id: "connection-15",
              },
              id: "connection-44",
              state: 3,
              transferChannel: {
                channelId: "channel-60",
                counterPartyChannelId: "channel-13",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "elysicstestnet-1": {
              client_id: "07-tendermint-69",
              counterparty: {
                client_id: "07-tendermint-19",
                connection_id: "connection-11",
              },
              id: "connection-46",
              state: 3,
              transferChannel: {
                channelId: "channel-61",
                counterPartyChannelId: "channel-12",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            "mocha-4": {
              client_id: "07-tendermint-367",
              counterparty: {
                client_id: "07-tendermint-367",
                connection_id: "connection-26",
              },
              id: "connection-281",
              state: 3,
              transferChannel: {
                channelId: "channel-38",
                counterPartyChannelId: "channel-78",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
            provider: {
              client_id: "07-tendermint-70",
              counterparty: {
                client_id: "07-tendermint-317",
                connection_id: "connection-225",
              },
              id: "connection-48",
              state: 3,
              transferChannel: {
                channelId: "channel-62",
                counterPartyChannelId: "channel-389",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          icaEnabled: true,
          icqEnabled: false,
          namespace: "cosmos",
          pfmEnabled: true,
          reference: "stride-internal-1",
          stakingTokens: [
            {
              denom: "ustrd",
            },
          ],
        },
      },
      feeConfig: {
        feeCollector: "agoric1a659t9fem9vpux6anq8877jh0dz6dtzj7g06r7",
        offBoardRate: {
          denominator: "100",
          numerator: "10",
        },
        onBoardRate: {
          denominator: "100",
          numerator: "20",
        },
      },
    },
  },
]);
const customManifest = {
  startElys: {
    consume: {
      agoricNames: true,
      board: true,
      chainStorage: true,
      chainTimerService: true,
      cosmosInterchainService: true,
      localchain: true,
      startUpgradable: true,
    },
    installation: {
      consume: {
        ElysContract: true,
      },
    },
    instance: {
      produce: {
        ElysContract: true,
      },
    },
  },
};

// Make a behavior function and "export" it by way of script completion value.
// It is constructed by an anonymous invocation to ensure the absence of a global binding
// for makeCoreProposalBehavior, which may not be necessary but preserves behavior pre-dating
// https://github.com/Agoric/agoric-sdk/pull/8712 .
const behavior = (({
  manifestBundleRef,
  getManifestCall: [manifestGetterName, ...manifestGetterArgs],
  customManifest,
  E,
  log = console.info,
  customRestoreRef,
}) => {
  const { entries, fromEntries } = Object;

  /**
   * Given an object whose properties may be promise-valued, return a promise
   * for an analogous object in which each such value has been replaced with its
   * fulfillment.
   * This is a non-recursive form of endo `deeplyFulfilled`.
   *
   * @template T
   * @param {{[K in keyof T]: (T[K] | Promise<T[K]>)}} obj
   * @returns {Promise<T>}
   */
  const shallowlyFulfilled = async obj => {
    if (!obj) {
      return obj;
    }
    const awaitedEntries = await Promise.all(
      entries(obj).map(async ([key, valueP]) => {
        const value = await valueP;
        return [key, value];
      }),
    );
    return fromEntries(awaitedEntries);
  };

  const makeRestoreRef = (vatAdminSvc, zoe) => {
    /** @type {(ref: import\('./externalTypes.js').ManifestBundleRef) => Promise<Installation<unknown>>} */
    const defaultRestoreRef = async bundleRef => {
      // extract-proposal.js creates these records, and bundleName is
      // the optional name under which the bundle was installed into
      // config.bundles
      const bundleIdP =
        'bundleName' in bundleRef
          ? E(vatAdminSvc).getBundleIDByName(bundleRef.bundleName)
          : bundleRef.bundleID;
      const bundleID = await bundleIdP;
      const label = bundleID.slice(0, 8);
      return E(zoe).installBundleID(bundleID, label);
    };
    return defaultRestoreRef;
  };

  /** @param {ChainBootstrapSpace & BootstrapPowers & { evaluateBundleCap: any }} powers */
  const coreProposalBehavior = async powers => {
    // NOTE: `powers` is expected to match or be a superset of the above `permits` export,
    // which should therefore be kept in sync with this deconstruction code.
    // HOWEVER, do note that this function is invoked with at least the *union* of powers
    // required by individual moduleBehaviors declared by the manifest getter, which is
    // necessary so it can use `runModuleBehaviors` to provide the appropriate subset to
    // each one (see ./writeCoreEvalParts.js).
    // Handle `powers` with the requisite care.
    const {
      consume: { vatAdminSvc, zoe, agoricNamesAdmin },
      evaluateBundleCap,
      installation: { produce: produceInstallations },
      modules: {
        utils: { runModuleBehaviors },
      },
    } = powers;

    // Get the on-chain installation containing the manifest and behaviors.
    log('evaluateBundleCap', {
      manifestBundleRef,
      manifestGetterName,
      vatAdminSvc,
    });
    let bcapP;
    if ('bundleName' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getNamedBundleCap(manifestBundleRef.bundleName);
    } else if ('bundleID' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getBundleCap(manifestBundleRef.bundleID);
    } else {
      const keys = Reflect.ownKeys(manifestBundleRef).map(key =>
        typeof key === 'string' ? JSON.stringify(key) : String(key),
      );
      const keysStr = `[${keys.join(', ')}]`;
      throw Error(
        `bundleRef must have own bundleName or bundleID, missing in ${keysStr}`,
      );
    }
    const bundleCap = await bcapP;

    const proposalNS = await evaluateBundleCap(bundleCap);

    // Get the manifest and its metadata.
    log('execute', {
      manifestGetterName,
      bundleExports: Object.keys(proposalNS),
    });
    const restoreRef = customRestoreRef || makeRestoreRef(vatAdminSvc, zoe);
    const {
      manifest,
      options: rawOptions,
      installations: rawInstallations,
    } = await proposalNS[manifestGetterName](
      harden({ restoreRef }),
      ...manifestGetterArgs,
    );

    // Await promises in the returned options and installations records.
    const [options, installations] = await Promise.all(
      [rawOptions, rawInstallations].map(shallowlyFulfilled),
    );

    // Publish the installations for our dependencies.
    const installationEntries = entries(installations || {});
    if (installationEntries.length > 0) {
      const installAdmin = E(agoricNamesAdmin).lookupAdmin('installation');
      await Promise.all(
        installationEntries.map(([key, value]) => {
          produceInstallations[key].reset();
          produceInstallations[key].resolve(value);
          return E(installAdmin).update(key, value);
        }),
      );
    }

    // Evaluate the manifest.
    return runModuleBehaviors({
      // Remember that `powers` may be arbitrarily broad.
      allPowers: powers,
      behaviors: proposalNS,
      manifest: customManifest || manifest,
      makeConfig: (name, _permit) => {
        log('coreProposal:', name);
        return { options };
      },
    });
  };

  return coreProposalBehavior;
})({ manifestBundleRef, getManifestCall, customManifest, E });
behavior;
